language: cpp

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo apt-add-repository ppa:beineri/opt-qt-5.10.1-trusty
  - sudo apt-get update

install:
  - sudo apt-get install qt510-meta-full 

before_script:
  - source /opt/qt510/bin/qt510-env.sh
  - qmake

script:
   - make

